coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 5%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: false
      macro: false

ignore:
  - "tests/"
  - "docs/"
  - "*.pyc"
  - "*.pyo"
  - "*.pyd"
  - "__pycache__"
  - "*.so"
  - ".git"
  - ".tox"
  - ".venv"
  - ".env"
  - "venv/"
  - "env/"
  - ".venv/"
  - ".env/"

github_checks:
  annotations: true
