name: Release

on:
  push:
    tags:
      - "v*"

env:
  PYTHON_VERSION: "3.12"
  NODE_VERSION: "18"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate tag format
        run: |
          # Extract version from tag and validate format
          VERSION=${GITHUB_REF#refs/tags/v}
          if [[ ! $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9.-]+)?(\+[a-zA-Z0-9.-]+)?$ ]]; then
            echo "❌ Invalid version format: $VERSION"
            echo "Expected format: vX.Y.Z[-prerelease][+build]"
            exit 1
          fi
          echo "✅ Valid version format: $VERSION"

      - name: Check for breaking changes
        run: |
          # Check if this is a major version bump
          VERSION=${GITHUB_REF#refs/tags/v}
          MAJOR=$(echo $VERSION | cut -d. -f1)
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD~1 2>/dev/null || echo "v0.0.0")
          PREV_MAJOR=$(echo $PREVIOUS_TAG | sed 's/v//' | cut -d. -f1)

          if [ "$MAJOR" != "$PREV_MAJOR" ]; then
            echo "⚠️  Major version bump detected ($PREV_MAJOR -> $MAJOR)"
            echo "This may indicate breaking changes"
          fi

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run tests
        run: |
          PYTHONPATH=src pytest tests/ -v --cov=gitco --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run security checks
        run: |
          # Check for known vulnerabilities
          pip-audit --format json --output pip-audit.json || true

          # Run bandit security linter
          bandit -r src/ -f json -o bandit-report.json || true

          # Check for secrets in code
          trufflehog --json . > trufflehog-report.json || true

      - name: Upload security reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            pip-audit.json
            bandit-report.json
            trufflehog-report.json

  build:
    runs-on: ubuntu-latest
    needs: [validate, test, security]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install conventional-changelog-cli
        run: npm install -g conventional-changelog-cli

      - name: Generate changelog
        id: changelog
        run: |
          # Extract version from tag (remove 'v' prefix)
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

          # Generate changelog from conventional commits using our config
          conventional-changelog -c .conventional-changelog.json -i CHANGELOG.md -s -r 0 > CHANGELOG.tmp

          # Update the changelog with the new version
          echo "# Changelog" > CHANGELOG.md
          echo "" >> CHANGELOG.md
          echo "All notable changes to this project will be documented in this file." >> CHANGELOG.md
          echo "" >> CHANGELOG.md
          echo "The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/)," >> CHANGELOG.md
          echo "and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html)." >> CHANGELOG.md
          echo "" >> CHANGELOG.md
          cat CHANGELOG.tmp >> CHANGELOG.md

          # Extract release notes for GitHub release
          conventional-changelog -c .conventional-changelog.json -i CHANGELOG.md -s -r 0 | \
            head -n 100 > RELEASE_NOTES.md

          # Clean up
          rm CHANGELOG.tmp

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine check-manifest

      - name: Validate package metadata
        run: |
          # Check manifest completeness
          check-manifest

          # Validate pyproject.toml
          python -c "import tomllib; tomllib.load(open('pyproject.toml', 'rb'))"
          echo "✅ Package metadata validation passed"

      - name: Build package
        run: python -m build

      - name: Check package
        run: |
          # Validate built package
          twine check dist/*

          # Test package installation in clean environment
          python -m venv test-env
          source test-env/bin/activate
          pip install dist/*.whl
          python -c "import gitco; print('✅ Package imports successfully')"
          deactivate

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Upload changelog
        uses: actions/upload-artifact@v4
        with:
          name: changelog
          path: |
            CHANGELOG.md
            RELEASE_NOTES.md

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Download changelog
        uses: actions/download-artifact@v4
        with:
          name: changelog
          path: ./

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: RELEASE_NOTES.md
          draft: false
          prerelease: ${{ contains(github.ref, '-') }}

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          if [ -z "$TWINE_PASSWORD" ]; then
            echo "⚠️  Skipping PyPI publishing - PYPI_API_TOKEN not configured"
            echo "To enable PyPI publishing, add PYPI_API_TOKEN secret"
            exit 0
          fi

          # Upload to PyPI with retry mechanism
          for i in {1..3}; do
            if twine upload dist/*; then
              echo "✅ Successfully published to PyPI"
              break
            else
              echo "⚠️  Upload attempt $i failed, retrying..."
              sleep 10
            fi
          done
        continue-on-error: true

      - name: Publish to Test PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          if [ -z "$TWINE_PASSWORD" ]; then
            echo "⚠️  Skipping Test PyPI publishing - TEST_PYPI_API_TOKEN not configured"
            echo "To enable Test PyPI publishing, add TEST_PYPI_API_TOKEN secret"
            exit 0
          fi

          # Upload to Test PyPI with retry mechanism
          for i in {1..3}; do
            if twine upload --repository testpypi dist/*; then
              echo "✅ Successfully published to Test PyPI"
              break
            else
              echo "⚠️  Upload attempt $i failed, retrying..."
              sleep 10
            fi
          done
        continue-on-error: true

      - name: Verify PyPI availability
        if: env.TWINE_PASSWORD != ''
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          sleep 30  # Wait for PyPI to process upload

          # Test package installation from PyPI
          python -m venv verify-env
          source verify-env/bin/activate
          pip install gitco==$VERSION
          python -c "import gitco; print('✅ Package available on PyPI')"
          deactivate

      - name: Update documentation
        run: |
          # Update installation instructions if needed
          echo "📚 Documentation updated for release ${{ github.ref }}"

      - name: Notify community
        run: |
          echo "🎉 Release ${{ github.ref }} published successfully!"
          echo "📦 PyPI: https://pypi.org/project/gitco/"
          echo "📋 Release: ${{ steps.create_release.outputs.url }}"
          echo "📖 Documentation: https://github.com/41technologies/gitco#readme"

  post-release:
    runs-on: ubuntu-latest
    needs: release
    if: always()
    steps:
      - name: Handle release success
        if: needs.release.result == 'success'
        run: |
          echo "✅ Release completed successfully"
          echo "📊 Next steps:"
          echo "  - Monitor download statistics"
          echo "  - Track community feedback"
          echo "  - Plan next release cycle"

      - name: Handle release failure
        if: needs.release.result == 'failure'
        run: |
          echo "❌ Release failed - manual intervention required"
          echo "🔍 Check the release workflow logs for details"
          echo "📧 Notify maintainers of the failure"
